#!/usr/bin/env python3
"""emit_artifacts.py — regenerate the ready-to-apply redirect artifacts.

redirects.json is the single source of record for the legacy->new map; the
files under tools/reconcile/apply/ are DERIVED from it by this script and
must never be hand-edited (same doctrine as the consoles' CC_DATA). After
any change to redirects.json, re-run:

  python3 tools/reconcile/emit_artifacts.py

Emits, under tools/reconcile/apply/:
  cloudflare_bulk_redirects.csv   - paste into Cloudflare Bulk Redirects
                                    (Account Home -> Bulk Redirects); the
                                    recommended path once the legacy zone's
                                    nameservers move to the Cloudflare
                                    account that already owns the estate
  htaccess_okccosmeticsurgeon.txt - Apache fallback if the legacy host stays
                                    on its current origin
  cloudfront_function.js          - CloudFront Function (viewer-request)
                                    fallback for the practice-stack ship
                                    path, should the legacy domain be
                                    parked on the estate's distribution

Every artifact 301s path-for-path and ends with the host-level catch-all,
so no legacy URL - indexed or not - can escape the consolidation.
"""
from __future__ import annotations

import csv
import io
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
APPLY = HERE / "apply"
SRC = HERE / "redirects.json"

HEADER = "# GENERATED by tools/reconcile/emit_artifacts.py from redirects.json - do not hand-edit\n"


def load() -> dict:
    return json.loads(SRC.read_text(encoding="utf-8"))


def path_of(url: str) -> str:
    return "/" + re.sub(r"^https?://[^/]+/?", "", url)


def cloudflare(doc: dict) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    # Cloudflare bulk-redirect CSV columns:
    # source_url,target_url,status_code,preserve_query_string,include_subdomains,subpath_matching,preserve_path_suffix
    for rule in doc["rules"]:
        if rule["legacy_path"] == "/":
            continue  # the catch-all row below covers the homepage
        legacy_host = doc["legacy_host"]
        w.writerow([f"{legacy_host}{rule['legacy_path']}", rule["target_url"], 301,
                    "true", "true", "false", "false"])
    # host-level catch-all: any path not matched above lands on the brand homepage
    w.writerow([doc["legacy_host"] + "/", doc["fallback_target"], 301,
                "false", "true", "true", "false"])
    return ("# GENERATED by tools/reconcile/emit_artifacts.py from redirects.json - do not hand-edit\n"
            "# Cloudflare Bulk Redirects CSV - import at Account Home -> Bulk Redirects\n"
            "# catch-all row uses subpath matching so unmapped legacy paths still 301\n"
            + buf.getvalue())


def htaccess(doc: dict) -> str:
    lines = [HEADER,
             "RewriteEngine On", ""]
    for rule in doc["rules"]:
        if rule["legacy_path"] == "/":
            continue  # handled by the catch-all
        lines.append(f"RewriteRule ^{re.escape(rule['legacy_path'].lstrip('/'))}/?$ "
                     f"{rule['target_url']} [R=301,L]")
    lines += ["", "# catch-all: everything else on the legacy host -> brand homepage",
              f"RewriteRule ^ {doc['fallback_target']} [R=301,L]", ""]
    return "\n".join(lines)


def cloudfront(doc: dict) -> str:
    mapping = {r["legacy_path"].rstrip("/") or "/": r["target_url"] for r in doc["rules"]}
    return (
        "// GENERATED by tools/reconcile/emit_artifacts.py from redirects.json - do not hand-edit\n"
        "// CloudFront Function (viewer-request) for the okccosmeticsurgeon.com consolidation.\n"
        "// Attach only to a distribution serving the legacy hostname.\n"
        "var MAP = " + json.dumps(mapping, indent=2, ensure_ascii=True) + ";\n"
        "var FALLBACK = " + json.dumps(doc["fallback_target"]) + ";\n"
        "function handler(event) {\n"
        "  var uri = event.request.uri.replace(/\\/+$/, '') || '/';\n"
        "  var target = MAP[uri] || FALLBACK;\n"
        "  return {\n"
        "    statusCode: 301,\n"
        "    statusDescription: 'Moved Permanently',\n"
        "    headers: { location: { value: target } }\n"
        "  };\n"
        "}\n")


def main() -> None:
    doc = load()
    APPLY.mkdir(exist_ok=True)
    (APPLY / "cloudflare_bulk_redirects.csv").write_text(cloudflare(doc), encoding="utf-8")
    (APPLY / "htaccess_okccosmeticsurgeon.txt").write_text(htaccess(doc), encoding="utf-8")
    (APPLY / "cloudfront_function.js").write_text(cloudfront(doc), encoding="utf-8")
    print(f"emitted {len(doc['rules'])} rules + catch-all into {APPLY.relative_to(HERE.parents[1])}/")


if __name__ == "__main__":
    main()
